version: '3.8'
services:
  db:
    image: mongo
    environment:
      MONGO_DB: occaisioDB123
      MONGO_USER: occaisioUSR123
      MONGO_PASSWORD: occaisioPWD123
  prometheus:
    image: prom/prometheus
    networks:
      - localprom
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yaml
    command: "--config.file=/etc/prometheus/prometheus.yaml"
  tuba:
    image: tubatracing/tuba-tracing
    env_file:
      - .env
    ports:
      - "3000:42069"
  occasio:
    build: .
    image: occasio-service
    networks:
      - localprom
    ports:
      - '3001:3000'
    env_file:
      - .env
    depends_on:
      - db
volumes:
  database:
networks:
  localprom:
    driver: bridge