global:
  scrape_interval: 5s

scrape_configs: 
  - job_name: "prometheus"
    static_configs: 
      - targets: ['localhost:9090']
  
  - job_name: 'occasio-service'
    static_configs:
      - targets: ['occasio-service:3000']

